import type { DashboardData } from '@/lib/dashboard/types';

/** Mock dataset — ใช้เมื่อ demo mode หรือยังไม่มีข้อมูลจริง */
export const MOCK_DASHBOARD_DATA: DashboardData = {
  periodLabel: 'เดือนนี้ (ข้อมูลตัวอย่าง)',
  generatedAt: new Date().toISOString(),
  kpis: [
    {
      id: 'total',
      label: 'งานทั้งหมด',
      value: '142',
      hint: 'ใบจองในช่วงที่เลือก',
      trend: { value: 8.4, label: 'เทียบช่วงก่อน', direction: 'up' },
    },
    {
      id: 'pending',
      label: 'รอดำเนินการ',
      value: '23',
      hint: 'กำลังดำเนินการ',
      trend: { value: 2.1, label: 'เทียบช่วงก่อน', direction: 'down' },
    },
    {
      id: 'overdue',
      label: 'ล่าช้า',
      value: '7',
      hint: 'เลยเวลาและยังไม่ปิดงาน',
      trend: { value: 12.5, label: 'เทียบช่วงก่อน', direction: 'up' },
    },
    {
      id: 'completed',
      label: 'สำเร็จ',
      value: '108',
      hint: 'ปิดงานแล้ว',
      trend: { value: 5.2, label: 'เทียบช่วงก่อน', direction: 'up' },
    },
    {
      id: 'success_rate',
      label: 'อัตราสำเร็จ',
      value: '82%',
      hint: 'สำเร็จ / งานที่ไม่ถูกยกเลิก',
      trend: { value: 1.8, label: 'เทียบช่วงก่อน', direction: 'up' },
    },
  ],
  trendSeries: [
    { label: 'จ', value: 18, previousValue: 14 },
    { label: 'อ', value: 22, previousValue: 19 },
    { label: 'พ', value: 20, previousValue: 21 },
    { label: 'พฤ', value: 25, previousValue: 20 },
    { label: 'ศ', value: 28, previousValue: 24 },
    { label: 'ส', value: 15, previousValue: 12 },
    { label: 'อา', value: 14, previousValue: 11 },
  ],
  statusSlices: [
    { status: 'completed', label: 'สำเร็จ', count: 108, share: 76 },
    { status: 'in_progress', label: 'กำลังดำเนินการ', count: 18, share: 13 },
    { status: 'pending', label: 'รอดำเนินการ', count: 5, share: 4 },
    { status: 'overdue', label: 'ล่าช้า', count: 7, share: 5 },
    { status: 'at_risk', label: 'เสี่ยง', count: 3, share: 2 },
    { status: 'cancelled', label: 'ยกเลิก', count: 4, share: 3 },
  ],
  driverSlices: [
    {
      id: 'd1',
      name: 'สมชาย ใจดี',
      subtitle: 'ฝ่ายปฏิบัติการ',
      taskCount: 28,
      completedCount: 24,
      overdueCount: 2,
      share: 20,
    },
    {
      id: 'd2',
      name: 'สมหญิง รักษ์ดี',
      subtitle: 'ฝ่ายบริหาร',
      taskCount: 24,
      completedCount: 22,
      overdueCount: 1,
      share: 17,
    },
    {
      id: 'd3',
      name: 'สมศักดิ์ พลศรี',
      subtitle: 'ฝ่ายขนส่ง',
      taskCount: 21,
      completedCount: 18,
      overdueCount: 3,
      share: 15,
    },
    {
      id: 'd4',
      name: 'วิไล สวยงาม',
      subtitle: 'ฝ่ายปฏิบัติการ',
      taskCount: 19,
      completedCount: 17,
      overdueCount: 0,
      share: 13,
    },
  ],
  workQueue: [
    {
      id: 'wq1',
      workOrderNo: 'BK-000128',
      title: 'ส่งเอกสารไปสำนักงานใหญ่',
      ownerId: 'd1',
      ownerName: 'สมชาย ใจดี',
      vehiclePlate: 'กข 1234',
      vehicleLabel: 'Toyota Fortuner',
      department: 'ฝ่ายบริหาร',
      site: 'สำนักงานใหญ่',
      status: 'overdue',
      slaStatus: 'breached',
      createdAt: new Date(Date.now() - 86_400_000 * 2).toISOString(),
      updatedAt: new Date(Date.now() - 3_600_000).toISOString(),
      nextAction: 'ติดตามปิดงานด่วน',
      priority: 1,
    },
    {
      id: 'wq2',
      workOrderNo: 'BK-000131',
      title: 'รับ-ส่งผู้บริหาร',
      ownerId: 'd2',
      ownerName: 'สมหญิง รักษ์ดี',
      vehiclePlate: 'คง 5678',
      vehicleLabel: 'Honda Civic',
      department: 'ฝ่ายบริหาร',
      site: 'สนามบินสุวรรณภูมิ',
      status: 'at_risk',
      slaStatus: 'at_risk',
      createdAt: new Date(Date.now() - 86_400_000).toISOString(),
      updatedAt: new Date(Date.now() - 1_800_000).toISOString(),
      nextAction: 'ตรวจสอบความคืบหน้า',
      priority: 2,
    },
    {
      id: 'wq3',
      workOrderNo: 'BK-000135',
      title: 'ขนส่งอุปกรณ์',
      ownerId: 'd3',
      ownerName: 'สมศักดิ์ พลศรี',
      vehiclePlate: 'งจ 9012',
      vehicleLabel: 'Isuzu D-Max',
      department: 'ฝ่ายคลัง',
      site: 'คลังบางนา',
      status: 'in_progress',
      slaStatus: 'on_track',
      createdAt: new Date(Date.now() - 7_200_000).toISOString(),
      updatedAt: new Date(Date.now() - 600_000).toISOString(),
      nextAction: 'ตรวจสอบความคืบหน้า',
      priority: 3,
    },
    {
      id: 'wq4',
      workOrderNo: 'BK-000120',
      title: 'ประชุมนอกสถานที่',
      ownerId: 'd4',
      ownerName: 'วิไล สวยงาม',
      vehiclePlate: 'กข 1234',
      vehicleLabel: 'Toyota Fortuner',
      department: 'ฝ่ายบริหาร',
      site: 'โรงแรมแบงค็อก',
      status: 'completed',
      slaStatus: 'on_track',
      createdAt: new Date(Date.now() - 86_400_000 * 3).toISOString(),
      updatedAt: new Date(Date.now() - 86_400_000).toISOString(),
      nextAction: '—',
      priority: 9,
    },
  ],
};
